import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import AdminNavbar from "@/features/admin/components/AdminNavbar";
import AdminSidebar from "@/features/admin/components/AdminSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <>
        <AdminNavbar />
        <div className="flex">

        <AdminSidebar />
        <div className="p-2">

        {children} 
        </div>
        </div>
        </>
      
  );
}
